import type { Participant, AthleteResult, LiveState, AuditLog } from '../types/shooting';

export const INITIAL_LIVE_STATE: LiveState = {
    eventId: 'lakshya-2-0-finals',
    eventName: 'LAKSHYA 2.0 — ISSF 10M AIR RIFLE & PISTOL FINALS',
    discipline: '10m_rifle',
    stage: 'FINAL_LIVE',
    relay: 1,
    youtubeVideoId: 'jfKfPfyJRdk',
    streamTitle: 'LAKSHYA 2.0 OFFICIAL FINALS LIVE STREAM',
    streamStatus: 'LIVE BROADCAST ACTIVE',
    cameraName: 'MAIN TARGET RANGE CAM 01',
    timerTargetEpoch: null,
    timerDurationSeconds: 45 * 60,
    isTimerRunning: false,
    updatedAt: Date.now(),
};

// 16 Finalists: 8 Air Rifle + 8 Air Pistol
export const INITIAL_FINALISTS: Participant[] = [
    // 10M AIR RIFLE (8 Finalists)
    {
        id: 'r-01',
        name: 'Rahul Kumar',
        usn: '1RV22CS045',
        department: 'CSE',
        discipline: '10m_rifle',
        initialScore: 624.8,
        achievements: 'State Gold Medalist 2025 · Nationals Qualified',
    },
    {
        id: 'r-02',
        name: 'Arjun Singh',
        usn: '1RV22EC018',
        department: 'ECE',
        discipline: '10m_rifle',
        initialScore: 622.4,
        achievements: 'All India Inter-University Finalist',
    },
    {
        id: 'r-03',
        name: 'Vishal K',
        usn: '1RV22ME032',
        department: 'ME',
        discipline: '10m_rifle',
        initialScore: 620.1,
        achievements: 'State Championship Silver Medalist',
    },
    {
        id: 'r-04',
        name: 'Karan Shenoy',
        usn: '1RV22IS012',
        department: 'ISE',
        discipline: '10m_rifle',
        initialScore: 618.5,
        achievements: 'South Zone Gold Medalist',
    },
    {
        id: 'r-05',
        name: 'Akash Gowda',
        usn: '1RV22EE029',
        department: 'EEE',
        discipline: '10m_rifle',
        initialScore: 617.2,
        achievements: 'State Selection Rank #4',
    },
    {
        id: 'r-06',
        name: 'Rohit Verma',
        usn: '1RV22AI008',
        department: 'AI/ML',
        discipline: '10m_rifle',
        initialScore: 615.9,
        achievements: 'Inter-College Gold Medalist',
    },
    {
        id: 'r-07',
        name: 'Nikhil R',
        usn: '1RV22CV019',
        department: 'Civil',
        discipline: '10m_rifle',
        initialScore: 614.3,
        achievements: 'NCC Directorate Bronze Medalist',
    },
    {
        id: 'r-08',
        name: 'Siddharth M',
        usn: '1RV22BT005',
        department: 'Biotech',
        discipline: '10m_rifle',
        initialScore: 612.8,
        achievements: 'State Youth Finalist',
    },

    // 10M AIR PISTOL (8 Finalists)
    {
        id: 'p-01',
        name: 'Aditya Rao',
        usn: '1RV21CS011',
        department: 'CSE',
        discipline: '10m_pistol',
        initialScore: 579.0,
        achievements: 'National Marksmanship Gold Medalist',
    },
    {
        id: 'p-02',
        name: 'Manoj Hegde',
        usn: '1RV21EC042',
        department: 'ECE',
        discipline: '10m_pistol',
        initialScore: 576.4,
        achievements: 'State Pistol Gold Medalist 2024',
    },
    {
        id: 'p-03',
        name: 'Varun Sharma',
        usn: '1RV21ME022',
        department: 'ME',
        discipline: '10m_pistol',
        initialScore: 574.8,
        achievements: 'All India University Silver',
    },
    {
        id: 'p-04',
        name: 'Pranav Joshi',
        usn: '1RV21IS035',
        department: 'ISE',
        discipline: '10m_pistol',
        initialScore: 572.1,
        achievements: 'South Zone Championship Finalist',
    },
    {
        id: 'p-05',
        name: 'Suhas K',
        usn: '1RV21EE017',
        department: 'EEE',
        discipline: '10m_pistol',
        initialScore: 570.5,
        achievements: 'State Bronze Medalist',
    },
    {
        id: 'p-06',
        name: 'Deepak N',
        usn: '1RV21AI015',
        department: 'AI/ML',
        discipline: '10m_pistol',
        initialScore: 568.2,
        achievements: 'Inter-College Silver Medalist',
    },
    {
        id: 'p-07',
        name: 'Chetan B',
        usn: '1RV21CH009',
        department: 'Chemical',
        discipline: '10m_pistol',
        initialScore: 566.0,
        achievements: 'State Selection Rank #7',
    },
    {
        id: 'p-08',
        name: 'Tarun Reddy',
        usn: '1RV21AE004',
        department: 'Aerospace',
        discipline: '10m_pistol',
        initialScore: 564.7,
        achievements: 'NCC Inter-Battalion Gold',
    },
];

// Initial AthleteResults converted from Finalists with initial clean finals state
export const INITIAL_ATHLETE_RESULTS: AthleteResult[] = INITIAL_FINALISTS.map((f, idx) => {
    return {
        participantId: f.id,
        name: f.name,
        usn: f.usn,
        department: f.department,
        discipline: f.discipline,
        photoUrl: f.photoUrl || '',
        achievements: f.achievements || '',
        initialScore: f.initialScore,
        shots: [],
        finalTotal: 0,
        liveTotalScore: 0,
        finalRank: (idx % 8) + 1,
        finalStatus: 'LIVE',
        laggingBy: '—',
    };
});

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
    {
        id: 'log-init-1',
        timestamp: Date.now() - 3600000,
        actorName: 'System Officer',
        actorRole: 'ADMIN',
        action: 'FINALISTS_VERIFIED',
        reason: '16 Finalists verified and loaded into competition engine for 10M Rifle and Pistol',
    },
];
